# -*- coding: utf-8 -*-
"""Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNb2gjizuj6lWY3I4f2HGqI1zEpZhiHH
"""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/"

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os
import random
from tqdm import tqdm

# ===================================================================
# 1. THE DATASET CLASS (REMAINS THE SAME)
# ===================================================================
class LungNoduleDataset(Dataset):
    """
    PyTorch Dataset for loading 3D lung scans.
    MODIFIED to extract random 3D patches to avoid memory errors.
    """
    def __init__(self, data_dir, masks_dir, patch_size=(96, 96, 96)):
        self.data_dir = data_dir
        self.masks_dir = masks_dir
        self.patch_size = patch_size

        mask_uids = {f.replace('_nodule_mask.npy', '') for f in os.listdir(masks_dir)}
        scan_files = {f.replace('_processed_lung.npy', '') for f in os.listdir(data_dir)}

        self.available_uids = sorted(list(mask_uids.intersection(scan_files)))

        print(f"Found {len(self.available_uids)} scans with corresponding nodule masks.")

    def __len__(self):
        return len(self.available_uids)

    def __getitem__(self, idx):
        uid = self.available_uids[idx]

        scan_path = os.path.join(self.data_dir, f"{uid}_processed_lung.npy")
        mask_path = os.path.join(self.masks_dir, f"{uid}_nodule_mask.npy")

        # Load the full 3D arrays
        scan = np.load(scan_path)
        mask = np.load(mask_path)

        # --- Patching Logic ---
        depth, height, width = scan.shape
        pd, ph, pw = self.patch_size

        z = random.randint(0, depth - pd)
        y = random.randint(0, height - ph)
        x = random.randint(0, width - pw)

        scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]
        mask_patch = mask[z:z+pd, y:y+ph, x:x+pw]

        # Convert to PyTorch tensors and add channel dimension
        scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).float()
        mask_tensor = torch.from_numpy(mask_patch).unsqueeze(0).float()

        return scan_tensor, mask_tensor

# ===================================================================
# 2. THE MODEL ARCHITECTURE (REPLACED WITH VNET)
# ===================================================================
class ConvBlock(nn.Module):
    """
    A single convolutional block for V-Net, including convolution, PReLU activation, and dropout.
    """
    def __init__(self, in_channels, out_channels, num_convs=1):
        super(ConvBlock, self).__init__()
        layers = []
        for i in range(num_convs):
            layers.append(nn.Conv3d(in_channels if i == 0 else out_channels, out_channels, kernel_size=5, padding=2))
            layers.append(nn.PReLU(out_channels))
        self.conv_block = nn.Sequential(*layers)

    def forward(self, x):
        return self.conv_block(x)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1, num_features=16):
        super(VNet, self).__init__()

        # Contracting Path (Encoder)
        self.down_conv1 = ConvBlock(in_channels, num_features, num_convs=1)
        self.down_pool1 = nn.Conv3d(num_features, num_features * 2, kernel_size=2, stride=2)

        self.down_conv2 = ConvBlock(num_features * 2, num_features * 2, num_convs=2)
        self.down_pool2 = nn.Conv3d(num_features * 2, num_features * 4, kernel_size=2, stride=2)

        self.down_conv3 = ConvBlock(num_features * 4, num_features * 4, num_convs=3)
        self.down_pool3 = nn.Conv3d(num_features * 4, num_features * 8, kernel_size=2, stride=2)

        self.down_conv4 = ConvBlock(num_features * 8, num_features * 8, num_convs=3)
        self.down_pool4 = nn.Conv3d(num_features * 8, num_features * 16, kernel_size=2, stride=2)

        self.bottom_conv = ConvBlock(num_features * 16, num_features * 16, num_convs=3)

        # Expanding Path (Decoder)
        self.up_deconv4 = nn.ConvTranspose3d(num_features * 16, num_features * 8, kernel_size=2, stride=2)
        self.up_conv4 = ConvBlock(num_features * 16, num_features * 8, num_convs=3)

        self.up_deconv3 = nn.ConvTranspose3d(num_features * 8, num_features * 4, kernel_size=2, stride=2)
        self.up_conv3 = ConvBlock(num_features * 8, num_features * 4, num_convs=3)

        self.up_deconv2 = nn.ConvTranspose3d(num_features * 4, num_features * 2, kernel_size=2, stride=2)
        self.up_conv2 = ConvBlock(num_features * 4, num_features * 2, num_convs=2)

        self.up_deconv1 = nn.ConvTranspose3d(num_features * 2, num_features, kernel_size=2, stride=2)
        self.up_conv1 = ConvBlock(num_features * 2, num_features, num_convs=1)

        # Output layer
        self.final_conv = nn.Conv3d(num_features, out_channels, kernel_size=1)

    def forward(self, x):
        # Contracting Path
        x1 = self.down_conv1(x)
        p1 = self.down_pool1(x1)

        x2 = self.down_conv2(p1)
        p2 = self.down_pool2(x2)

        x3 = self.down_conv3(p2)
        p3 = self.down_pool3(x3)

        x4 = self.down_conv4(p3)
        p4 = self.down_pool4(x4)

        x_bottom = self.bottom_conv(p4)

        # Expanding Path
        u4 = self.up_deconv4(x_bottom)
        cat4 = torch.cat([u4, x4], dim=1)
        u4 = self.up_conv4(cat4)

        u3 = self.up_deconv3(u4)
        cat3 = torch.cat([u3, x3], dim=1)
        u3 = self.up_conv3(cat3)

        u2 = self.up_deconv2(u3)
        cat2 = torch.cat([u2, x2], dim=1)
        u2 = self.up_conv2(cat2)

        u1 = self.up_deconv1(u2)
        cat1 = torch.cat([u1, x1], dim=1)
        u1 = self.up_conv1(cat1)

        return self.final_conv(u1)

# ===================================================================
# 3. THE TRAINING LOOP (MODIFIED TO USE VNET)
# ===================================================================
if __name__ == '__main__':
    # --- Training Configuration ---
    processed_data_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/processed_data/"
    ground_truth_masks_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/ground_truth_masks/"

    LEARNING_RATE = 1e-4
    BATCH_SIZE = 1
    NUM_EPOCHS = 25
    PATCH_SIZE = (96, 96, 96)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Using device: {DEVICE}")

    # --- Setup Dataset and DataLoader ---
    dataset = LungNoduleDataset(
        data_dir=processed_data_dir,
        masks_dir=ground_truth_masks_dir,
        patch_size=PATCH_SIZE
    )

    dataloader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0 # Changed num_workers to 0
    )

    # --- Setup Model, Loss, and Optimizer ---
    # REPLACED AttentionUNet3D() with VNet()
    model = VNet().to(DEVICE)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    # --- Start Training ---
    print("\n--- Starting Training ---")
    for epoch in range(NUM_EPOCHS):
        loop = tqdm(dataloader, leave=True)
        loop.set_description(f"Epoch [{epoch+1}/{NUM_EPOCHS}]")

        running_loss = 0.0
        for scans, masks in loop:
            scans = scans.to(DEVICE)
            masks = masks.to(DEVICE)

            # Forward pass
            outputs = model(scans)
            loss = loss_fn(outputs, masks)

            # Backward pass and optimization
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            loop.set_postfix(loss=loss.item())

        avg_loss = running_loss / len(dataloader)
        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] - Average Loss: {avg_loss:.4f}")

    print("--- Training Finished ---")

    # --- Save the Trained Model ---
    save_directory = "/content/drive/My Drive/Lung Cancer Project/"
    model_name = "vnet_3d_nodule_segmentation.pth"
    model_save_path = os.path.join(save_directory, model_name)
    os.makedirs(save_directory, exist_ok=True)
    model_save_path = "vnet_3d_nodule_segmentation.pth"
    torch.save(model.state_dict(), model_save_path)
    print(f"✅ Model saved to {model_save_path}")

import shutil

source_path = "/content/vnet_3d_nodule_segmentation.pth"
destination_path = "/content/drive/My Drive/Lung Cancer Project/vnet_3d_nodule_segmentation.pth"

# Move the file from source to destination
shutil.move(source_path, destination_path)
print(f"✅ Model successfully moved to Google Drive at {destination_path}")

import torch
import torch.nn as nn
import numpy as np
import os

# Make sure the model class definitions are in the notebook
# (You can copy the VNet and ConvBlock classes from your training script)

# --- Define the Dice Score Function ---
def dice_coefficient(pred, target, smooth=1e-6):
    """Calculates the Dice coefficient (F1 score) for a single prediction."""
    pred = pred.contiguous()
    target = target.contiguous()

    intersection = (pred * target).sum()
    dice = (2. * intersection + smooth) / (pred.sum() + target.sum() + smooth)

    return dice.item()

# --- Load Your Trained Model ---
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Instantiate the V-Net model architecture
model = VNet().to(DEVICE) # Changed to VNet()

# Path to your saved V-Net model file
model_path = "/content/drive/My Drive/Lung Cancer Project/vnet_3d_nodule_segmentation.pth" # Changed model path
model.load_state_dict(torch.load(model_path))
model.eval() # Set the model to evaluation mode (very important!)

print("Model loaded successfully.")

# --- 3. Load a Test Sample ---
# IMPORTANT: Use a scan that was NOT used for training
# These paths must be correct for a file pair in your preprocessed data
test_scan_path = "/content/testscan/processed_lung2.npy"
test_mask_path = "/content/testscan/create_ground_truth_masks2.npy"

# Load the numpy arrays
test_scan = np.load(test_scan_path)
test_mask = np.load(test_mask_path)

# Convert to tensors and add batch/channel dimensions [B, C, D, H, W]
test_scan_tensor = torch.from_numpy(test_scan).unsqueeze(0).unsqueeze(0).float().to(DEVICE)
test_mask_tensor = torch.from_numpy(test_mask).unsqueeze(0).unsqueeze(0).float().to(DEVICE)

# --- 4. Make a Prediction (Inference) ---
with torch.no_grad(): # Disable gradient calculations for speed
    # Let's crop a patch from the test scan, same size as training
    # You may need to adjust the starting indices (50, 150, 150)
    test_patch = test_scan_tensor[:, :, 50:50+96, 150:150+96, 150:150+96]
    true_mask_patch = test_mask_tensor[:, :, 50:50+96, 150:150+96, 150:150+96]

    # Get the model's raw output (logits)
    prediction_logits = model(test_patch)

    # Convert logits to a binary mask (0s and 1s)
    prediction_prob = torch.sigmoid(prediction_logits)
    prediction_mask = (prediction_prob > 0.5).float()

# --- 5. Calculate and Print the Dice Score ---
score = dice_coefficient(prediction_mask, true_mask_patch)
print(f"\nDice Score for the test patch: {score:.4f}")

!ls "/content/drive/My Drive/Lung Cancer Project/"

import matplotlib.pyplot as plt

# Choose a slice from the middle of the 3D patch to display
slice_index = 48 # This is the middle slice of a 96-depth patch

# Get the specific 2D slices for plotting
# .squeeze() removes the batch and channel dimensions
# .cpu().numpy() moves the data from GPU to CPU for plotting
scan_slice = test_patch.squeeze().cpu().numpy()[slice_index, :, :]
truth_slice = true_mask_patch.squeeze().cpu().numpy()[slice_index, :, :]
prediction_slice = prediction_mask.squeeze().cpu().numpy()[slice_index, :, :]

# --- Create the plot ---
# Added an extra subplot for the overlay
fig, axes = plt.subplots(1, 4, figsize=(20, 6))

# Plot 1: Original Scan Slice
axes[0].imshow(scan_slice, cmap='gray')
axes[0].set_title('Original Scan Patch', fontsize=16)
axes[0].axis('off')

# Plot 2: Ground Truth Mask
axes[1].imshow(truth_slice, cmap='viridis') # Changed colormap to viridis
axes[1].set_title('Ground Truth Mask', fontsize=16)
axes[1].axis('off')

# Plot 3: Model's Prediction
axes[2].imshow(prediction_slice, cmap='viridis') # Changed colormap to viridis
axes[2].set_title("Model's Prediction", fontsize=16)
axes[2].axis('off')

# Plot 4: Prediction Overlay
axes[3].imshow(scan_slice, cmap='gray')
axes[3].imshow(prediction_slice, cmap='viridis', alpha=0.5) # Overlay with transparency
axes[3].set_title('Prediction Overlay', fontsize=16)
axes[3].axis('off')

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os
import random
from tqdm import tqdm # For a nice progress bar
from google.colab import drive # Import the necessary library

# ===================================================================
# MOUNT GOOGLE DRIVE
# ===================================================================
# This command is crucial for Colab to access your files.
# It will prompt you to authorize access to your Google Drive.
drive.mount('/content/drive')

# ===================================================================
# 1. THE DATASET CLASS
# ===================================================================
class LungNoduleDataset(Dataset):
    """
    PyTorch Dataset for loading 3D lung scans with random 3D patching.
    """
    def __init__(self, data_dir, masks_dir, patch_size=(96, 96, 96)):
        self.data_dir = data_dir
        self.masks_dir = masks_dir

        # Check if the directories exist before listing their contents
        if not os.path.exists(self.data_dir):
            raise FileNotFoundError(f"Data directory not found: {self.data_dir}")
        if not os.path.exists(self.masks_dir):
            raise FileNotFoundError(f"Masks directory not found: {self.masks_dir}")

        self.patch_size = patch_size

        mask_uids = {f.replace('_nodule_mask.npy', '') for f in os.listdir(masks_dir)}
        scan_files = {f.replace('_processed_lung.npy', '') for f in os.listdir(data_dir)}

        self.available_uids = sorted(list(mask_uids.intersection(scan_files)))

        print(f"Found {len(self.available_uids)} scans with corresponding nodule masks.")

    def __len__(self):
        return len(self.available_uids)

    def __getitem__(self, idx):
        uid = self.available_uids[idx]
        scan_path = os.path.join(self.data_dir, f"{uid}_processed_lung.npy")
        mask_path = os.path.join(self.masks_dir, f"{uid}_nodule_mask.npy")

        scan = np.load(scan_path)
        mask = np.load(mask_path)

        depth, height, width = scan.shape
        pd, ph, pw = self.patch_size

        z = random.randint(0, depth - pd)
        y = random.randint(0, height - ph)
        x = random.randint(0, width - pw)

        scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]
        mask_patch = mask[z:z+pd, y:y+ph, x:x+pw]

        scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).float()
        mask_tensor = torch.from_numpy(mask_patch).unsqueeze(0).float()

        return scan_tensor, mask_tensor

# ===================================================================
# 2. THE 3D-VNET ARCHITECTURE
# ===================================================================
def passthrough_block(in_channels, out_channels, kernel_size, stride, padding):
    return nn.Sequential(
        nn.Conv3d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm3d(out_channels)
    )

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ResidualBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels)
        )
        self.relu = nn.ReLU(inplace=True)
        self.passthrough = passthrough_block(in_channels, out_channels, kernel_size=1, stride=1, padding=0) if in_channels != out_channels else None

    def forward(self, x):
        residual = self.passthrough(x) if self.passthrough else x
        return self.relu(self.conv_block(x) + residual)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(VNet, self).__init__()
        self.down_conv1 = ResidualBlock(in_channels, 16)
        self.down_pool1 = passthrough_block(16, 32, kernel_size=2, stride=2, padding=0)

        self.down_conv2 = ResidualBlock(32, 32)
        self.down_pool2 = passthrough_block(32, 64, kernel_size=2, stride=2, padding=0)

        self.down_conv3 = ResidualBlock(64, 64)
        self.down_pool3 = passthrough_block(64, 128, kernel_size=2, stride=2, padding=0)

        self.down_conv4 = ResidualBlock(128, 128)
        self.down_pool4 = passthrough_block(128, 256, kernel_size=2, stride=2, padding=0)

        self.bottleneck = ResidualBlock(256, 256)

        self.up_deconv4 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.up_conv4 = ResidualBlock(256, 128)

        self.up_deconv3 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.up_conv3 = ResidualBlock(128, 64)

        self.up_deconv2 = nn.ConvTranspose3d(64, 32, kernel_size=2, stride=2)
        self.up_conv2 = ResidualBlock(64, 32)

        self.up_deconv1 = nn.ConvTranspose3d(32, 16, kernel_size=2, stride=2)
        self.up_conv1 = ResidualBlock(32, 16)

        self.final_conv = nn.Conv3d(16, out_channels, kernel_size=1)

    def forward(self, x):
        d1 = self.down_conv1(x)
        d2 = self.down_pool1(d1); d2 = self.down_conv2(d2)
        d3 = self.down_pool2(d2); d3 = self.down_conv3(d3)
        d4 = self.down_pool3(d3); d4 = self.down_conv4(d4)

        bottleneck_out = self.down_pool4(d4)
        bottleneck_out = self.bottleneck(bottleneck_out)

        u4 = self.up_deconv4(bottleneck_out); u4 = torch.cat((u4, d4), dim=1); u4 = self.up_conv4(u4)
        u3 = self.up_deconv3(u4); u3 = torch.cat((u3, d3), dim=1); u3 = self.up_conv3(u3)
        u2 = self.up_deconv2(u3); u2 = torch.cat((u2, d2), dim=1); u2 = self.up_conv2(u2)
        u1 = self.up_deconv1(u2); u1 = torch.cat((u1, d1), dim=1); u1 = self.up_conv1(u1)

        out = self.final_conv(u1)
        return out

# ===================================================================
# 3. THE TRAINING LOOP
# ===================================================================
if __name__ == '__main__':
    # --- Training Configuration ---
    # !! IMPORTANT: VERIFY THESE PATHS !!
    # You must ensure these paths match your Google Drive structure exactly.
    processed_data_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/processed_data/"
    ground_truth_masks_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/ground_truth_masks/"

    LEARNING_RATE = 1e-4
    BATCH_SIZE = 1
    NUM_EPOCHS = 25
    PATCH_SIZE = (96, 96, 96)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Using device: {DEVICE}")

    # --- Setup Dataset and DataLoader ---
    dataset = LungNoduleDataset(
        data_dir=processed_data_dir,
        masks_dir=ground_truth_masks_dir,
        patch_size=PATCH_SIZE
    )

    dataloader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2
    )

    # --- Setup Model, Loss, and Optimizer ---
    model = VNet().to(DEVICE)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    # --- Start Training ---
    print("\n--- Starting Training ---")
    for epoch in range(NUM_EPOCHS):
        loop = tqdm(dataloader, leave=True)
        loop.set_description(f"Epoch [{epoch+1}/{NUM_EPOCHS}]")

        running_loss = 0.0
        for scans, masks in loop:
            scans = scans.to(DEVICE)
            masks = masks.to(DEVICE)

            # Forward pass
            outputs = model(scans)
            loss = loss_fn(outputs, masks)

            # Backward pass and optimization
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            loop.set_postfix(loss=loss.item())

        avg_loss = running_loss / len(dataloader)
        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] - Average Loss: {avg_loss:.4f}")

    print("--- Training Finished ---")

    # --- Save the Trained Model ---
    save_directory = "/content/drive/My Drive/Lung Cancer Project/"
    model_name = "VNet_Nodule.pth"
    model_save_path = os.path.join(save_directory, model_name)

    os.makedirs(save_directory, exist_ok=True)

    torch.save(model.state_dict(), model_save_path)
    print(f"✅ Model saved to {model_save_path}")

import torch
import torch.nn as nn
import numpy as np
import os
import random
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader

# ===================================================================
# 1. THE DATASET CLASS (REMAINS THE SAME)
# ===================================================================
class LungNoduleDataset(Dataset):
    """
    PyTorch Dataset for loading 3D lung scans with random 3D patching.
    """
    def __init__(self, data_dir, masks_dir, patch_size=(96, 96, 96)):
        self.data_dir = data_dir
        self.masks_dir = masks_dir
        self.patch_size = patch_size
        if not os.path.exists(self.data_dir) or not os.path.exists(self.masks_dir):
            raise FileNotFoundError("Data or masks directory not found. Please check your paths.")
        mask_uids = {f.replace('_nodule_mask.npy', '') for f in os.listdir(masks_dir)}
        scan_files = {f.replace('_processed_lung.npy', '') for f in os.listdir(data_dir)}
        self.available_uids = sorted(list(mask_uids.intersection(scan_files)))
        print(f"Found {len(self.available_uids)} scans with corresponding nodule masks.")

    def __len__(self): return len(self.available_uids)

    def __getitem__(self, idx):
        uid = self.available_uids[idx]
        scan_path = os.path.join(self.data_dir, f"{uid}_processed_lung.npy")
        mask_path = os.path.join(self.masks_dir, f"{uid}_nodule_mask.npy")
        scan = np.load(scan_path); mask = np.load(mask_path)
        depth, height, width = scan.shape
        pd, ph, pw = self.patch_size
        z = random.randint(0, depth - pd); y = random.randint(0, height - ph); x = random.randint(0, width - pw)
        scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]
        mask_patch = mask[z:z+pd, y:y+ph, x:x+pw]
        scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).float()
        mask_tensor = torch.from_numpy(mask_patch).unsqueeze(0).float()
        return scan_tensor, mask_tensor

# ===================================================================
# 2. THE 3D-VNET ARCHITECTURE (Required to load the model)
# ===================================================================
def passthrough_block(in_channels, out_channels, kernel_size, stride, padding):
    return nn.Sequential(
        nn.Conv3d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm3d(out_channels)
    )

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ResidualBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels)
        )
        self.relu = nn.ReLU(inplace=True)
        self.passthrough = passthrough_block(in_channels, out_channels, kernel_size=1, stride=1, padding=0) if in_channels != out_channels else None

    def forward(self, x):
        residual = self.passthrough(x) if self.passthrough else x
        return self.relu(self.conv_block(x) + residual)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(VNet, self).__init__()
        self.down_conv1 = ResidualBlock(in_channels, 16)
        self.down_pool1 = passthrough_block(16, 32, kernel_size=2, stride=2, padding=0)

        self.down_conv2 = ResidualBlock(32, 32)
        self.down_pool2 = passthrough_block(32, 64, kernel_size=2, stride=2, padding=0)

        self.down_conv3 = ResidualBlock(64, 64)
        self.down_pool3 = passthrough_block(64, 128, kernel_size=2, stride=2, padding=0)

        self.down_conv4 = ResidualBlock(128, 128)
        self.down_pool4 = passthrough_block(128, 256, kernel_size=2, stride=2, padding=0)

        self.bottleneck = ResidualBlock(256, 256)

        self.up_deconv4 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.up_conv4 = ResidualBlock(256, 128)

        self.up_deconv3 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.up_conv3 = ResidualBlock(128, 64)

        self.up_deconv2 = nn.ConvTranspose3d(64, 32, kernel_size=2, stride=2)
        self.up_conv2 = ResidualBlock(64, 32)

        self.up_deconv1 = nn.ConvTranspose3d(32, 16, kernel_size=2, stride=2)
        self.up_conv1 = ResidualBlock(32, 16)

        self.final_conv = nn.Conv3d(16, out_channels, kernel_size=1)

    def forward(self, x):
        d1 = self.down_conv1(x)
        d2 = self.down_pool1(d1); d2 = self.down_conv2(d2)
        d3 = self.down_pool2(d2); d3 = self.down_conv3(d3)
        d4 = self.down_pool3(d3); d4 = self.down_conv4(d4)

        bottleneck_out = self.down_pool4(d4)
        bottleneck_out = self.bottleneck(bottleneck_out)

        u4 = self.up_deconv4(bottleneck_out); u4 = torch.cat((u4, d4), dim=1); u4 = self.up_conv4(u4)
        u3 = self.up_deconv3(u4); u3 = torch.cat((u3, d3), dim=1); u3 = self.up_conv3(u3)
        u2 = self.up_deconv2(u3); u2 = torch.cat((u2, d2), dim=1); u2 = self.up_conv2(u2)
        u1 = self.up_deconv1(u2); u1 = torch.cat((u1, d1), dim=1); u1 = self.up_conv1(u1)

        out = self.final_conv(u1)
        return out

# ===================================================================
# 3. MAIN VISUALIZATION LOGIC
# ===================================================================
def visualize_predictions_with_circles(model, data_loader, device):
    images, masks = next(iter(data_loader))
    images, masks = images.to(device), masks.to(device)

    with torch.no_grad():
        predictions = model(images)
    preds_sigmoid = torch.sigmoid(predictions)
    predicted_masks = (preds_sigmoid > 0.5).float()

    images = images.cpu().numpy(); masks = masks.cpu().numpy(); predicted_masks = predicted_masks.cpu().numpy()

    num_samples_to_show = min(images.shape[0], 4)
    fig, axes = plt.subplots(num_samples_to_show, 1, figsize=(8, num_samples_to_show * 8))
    fig.suptitle("Model Predictions with Circular Overlays", fontsize=20)

    for i in range(num_samples_to_show):
        ax = axes[i] if num_samples_to_show > 1 else axes

        # Get the center slice for display
        center_slice_idx = images.shape[2] // 2
        img_slice = images[i, 0, center_slice_idx, :, :]

        ax.imshow(img_slice, cmap='gray')
        ax.set_xticks([]); ax.set_yticks([])
        ax.set_title(f"Sample {i+1}")

        # Find center of ground truth mask
        gt_mask = masks[i, 0, center_slice_idx, :, :]
        gt_coords = np.argwhere(gt_mask == 1)
        if len(gt_coords) > 0:
            gt_center_y, gt_center_x = gt_coords.mean(axis=0).astype(int)
            circle_gt = plt.Circle((gt_center_x, gt_center_y), 7, color='green', fill=False, linewidth=2)
            ax.add_patch(circle_gt)

        # Find center of prediction mask
        pred_mask = predicted_masks[i, 0, center_slice_idx, :, :]
        pred_coords = np.argwhere(pred_mask == 1)
        if len(pred_coords) > 0:
            pred_center_y, pred_center_x = pred_coords.mean(axis=0).astype(int)
            circle_pred = plt.Circle((pred_center_x, pred_center_y), 7, color='red', fill=False, linewidth=2)
            ax.add_patch(circle_pred)

    legend_elements = [
        plt.Line2D([0], [0], color='green', lw=2, label='Ground Truth'),
        plt.Line2D([0], [0], color='red', lw=2, label='Model Prediction')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=2, fontsize=14)
    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    plt.show()

# ===================================================================
# 4. SCRIPT EXECUTION
# ===================================================================
if __name__ == '__main__':
    # --- Configuration ---
    processed_data_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/processed_data/"
    ground_truth_masks_dir = "/content/drive/My Drive/Lung Cancer Project/Preprocessed_subset0/ground_truth_masks/"
    model_path = "/content/drive/My Drive/Lung Cancer Project/VNet_Nodule.pth"
    PATCH_SIZE = (96, 96, 96)
    BATCH_SIZE = 1
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    # --- Setup Dataset and DataLoader ---
    dataset = LungNoduleDataset(data_dir=processed_data_dir, masks_dir=ground_truth_masks_dir, patch_size=PATCH_SIZE)
    dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)

    # --- Load Model and Visualize ---
    model = VNet().to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()

    visualize_predictions_with_circles(model, dataloader, DEVICE)

import torch
import torch.nn as nn
import numpy as np
import os
import random
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Google Drive to access your saved model
drive.mount('/content/drive')

# ===================================================================
# 1. THE VNET MODEL ARCHITECTURE (Required for loading the model)
# Copied from the training cell to ensure architecture matches
# ===================================================================
def passthrough_block(in_channels, out_channels, kernel_size, stride, padding):
    return nn.Sequential(
        nn.Conv3d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm3d(out_channels)
    )

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ResidualBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels)
        )
        self.relu = nn.ReLU(inplace=True)
        self.passthrough = passthrough_block(in_channels, out_channels, kernel_size=1, stride=1, padding=0) if in_channels != out_channels else None

    def forward(self, x):
        residual = self.passthrough(x) if self.passthrough else x
        return self.relu(self.conv_block(x) + residual)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(VNet, self).__init__()
        self.down_conv1 = ResidualBlock(in_channels, 16)
        self.down_pool1 = passthrough_block(16, 32, kernel_size=2, stride=2, padding=0)

        self.down_conv2 = ResidualBlock(32, 32)
        self.down_pool2 = passthrough_block(32, 64, kernel_size=2, stride=2, padding=0)

        self.down_conv3 = ResidualBlock(64, 64)
        self.down_pool3 = passthrough_block(64, 128, kernel_size=2, stride=2, padding=0)

        self.down_conv4 = ResidualBlock(128, 128)
        self.down_pool4 = passthrough_block(128, 256, kernel_size=2, stride=2, padding=0)

        self.bottleneck = ResidualBlock(256, 256)

        self.up_deconv4 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.up_conv4 = ResidualBlock(256, 128)

        self.up_deconv3 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.up_conv3 = ResidualBlock(128, 64)

        self.up_deconv2 = nn.ConvTranspose3d(64, 32, kernel_size=2, stride=2)
        self.up_conv2 = ResidualBlock(64, 32)

        self.up_deconv1 = nn.ConvTranspose3d(32, 16, kernel_size=2, stride=2)
        self.up_conv1 = ResidualBlock(32, 16)

        self.final_conv = nn.Conv3d(16, out_channels, kernel_size=1)

    def forward(self, x):
        d1 = self.down_conv1(x)
        d2 = self.down_pool1(d1); d2 = self.down_conv2(d2)
        d3 = self.down_pool2(d2); d3 = self.down_conv3(d3)
        d4 = self.down_pool3(d3); d4 = self.down_conv4(d4)

        bottleneck_out = self.down_pool4(d4)
        bottleneck_out = self.bottleneck(bottleneck_out)

        u4 = self.up_deconv4(bottleneck_out); u4 = torch.cat((u4, d4), dim=1); u4 = self.up_conv4(u4)
        u3 = self.up_deconv3(u4); u3 = torch.cat((u3, d3), dim=1); u3 = self.up_conv3(u3)
        u2 = self.up_deconv2(u3); u2 = torch.cat((u2, d2), dim=1); u2 = self.up_conv2(u2)
        u1 = self.up_deconv1(u2); u1 = torch.cat((u1, d1), dim=1); u1 = self.up_conv1(u1)

        out = self.final_conv(u1)
        return out


# ===================================================================
# 2. DICE COEFFICIENT ACCURACY METRIC
# ===================================================================
def dice_coefficient(pred, target, smooth=1e-6):
    pred = pred.contiguous()
    target = target.contiguous()
    intersection = (pred * target).sum()
    dice = (2. * intersection + smooth) / (pred.sum() + target.sum() + smooth)
    return dice.item()

# ===================================================================
# 3. TEST AND VISUALIZATION
# ===================================================================
def test_and_visualize_overlay(model_path, test_scan_path, test_mask_path=None, patch_size=(96, 96, 96)):
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {DEVICE}")

    # --- Load the Model ---
    model = VNet().to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    print(f"✅ Model loaded successfully from {model_path}")

    # --- Load Test Data ---
    try:
        scan = np.load(test_scan_path)
    except FileNotFoundError:
        print(f"!!! Error: Could not find the test scan at: {test_scan_path}")
        return
    except Exception as e:
        print(f"!!! An error occurred while loading test scan: {e}")
        print(f"This could be due to a corrupted file or an unstable connection to Google Drive.")
        print(f"Please check the integrity of your files and your internet connection.")
        return


    # Extract a fixed patch from the scan
    depth, height, width = scan.shape
    pd, ph, pw = patch_size

    # Ensure patch size is not larger than the image dimensions
    if pd > depth or ph > height or pw > width:
         print(f"!!! Error: Patch size {patch_size} is larger than the scan dimensions {scan.shape}.")
         print("Please adjust the patch size or select a larger scan.")
         return

    z, y, x = (depth - pd) // 2, (height - ph) // 2, (width - pw) // 2

    # Ensure selected patch location is valid
    if z < 0 or y < 0 or x < 0 or z + pd > depth or y + ph > height or x + pw > width:
         print(f"!!! Warning: Fixed patch location ({z}, {y}, {x}) with size {patch_size} is out of bounds for scan dimensions {scan.shape}.")
         print("Attempting to use a random valid patch location instead.")
         z = random.randint(0, depth - pd)
         y = random.randint(0, height - ph)
         x = random.randint(0, width - pw)
         print(f"Using random valid patch location: ({z}, {y}, {x})")


    scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]


    # Load mask if provided
    mask_patch = None
    if test_mask_path:
        try:
            mask = np.load(test_mask_path)
            # Ensure patch size is not larger than the mask dimensions (should match scan)
            if pd > mask.shape[0] or ph > mask.shape[1] or pw > mask.shape[2]:
                 print(f"!!! Error: Patch size {patch_size} is larger than the mask dimensions {mask.shape}.")
                 print("Please ensure mask dimensions match scan dimensions.")
                 return
            mask_patch = mask[z:z+pd, y:y+ph, x:x+pw]
        except FileNotFoundError:
            print(f"!!! Error: Could not find the mask file at: {test_mask_path}")
        except Exception as e:
            print(f"!!! An error occurred while loading test mask: {e}")
            print(f"This could be due to a corrupted file or an unstable connection to Google Drive.")
            print(f"Please check the integrity of your files and your internet connection.")


    # Convert to tensor
    test_scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).unsqueeze(0).float().to(DEVICE)

    # --- Make Prediction and Calculate Score ---
    with torch.no_grad():
        prediction_logits = model(test_scan_tensor)
        prediction_probs = torch.sigmoid(prediction_logits)
        predicted_mask = (prediction_probs > 0.5).float()

    if test_mask_path and mask_patch is not None:
        test_mask_tensor = torch.from_numpy(mask_patch).unsqueeze(0).unsqueeze(0).float().to(DEVICE)
        score = dice_coefficient(predicted_mask, test_mask_tensor)
        print(f"\n✅ Dice Score for the test patch: {score:.4f}")
    else:
        print("\nNote: No Dice score calculated as no ground truth mask was provided or loaded successfully.")

    # --- Visualization with Differentiated Overlay ---
    print("\n--- Generating Visualization ---")

    slice_index = patch_size[0] // 2
    # Ensure slice index is within the bounds of the patch depth
    if slice_index >= patch_size[0]:
        slice_index = patch_size[0] - 1 # Use the last slice if middle is out of bounds


    scan_slice = scan_patch[slice_index, :, :]
    pred_mask_slice = predicted_mask.squeeze().cpu().numpy()[slice_index, :, :]

    fig, axes = plt.subplots(1, 2, figsize=(12, 6))

    # Plot 1: Original Scan
    axes[0].imshow(scan_slice, cmap='gray')
    axes[0].set_title('Original Input', fontsize=16)
    axes[0].axis('off')

    # Plot 2: Prediction with Red Overlay
    axes[1].imshow(scan_slice, cmap='gray')
    axes[1].imshow(pred_mask_slice, cmap='Reds', alpha=0.5)
    axes[1].set_title('Predicted Nodule (Red)', fontsize=16)
    axes[1].axis('off')

    plt.tight_layout()
    plt.show()

# ===================================================================
# 4. SCRIPT EXECUTION
# ===================================================================
if __name__ == '__main__':
    # !! UPDATE THIS PATH TO YOUR TRAINED MODEL IN GOOGLE DRIVE !!
    model_path = "/content/drive/My Drive/Lung Cancer Project/VNet_Nodule.pth"

    # These paths are for the files you will upload to Colab
    # !! UPDATE THESE PATHS TO YOUR ACTUAL TEST SCAN AND MASK FILES IN GOOGLE DRIVE !!
    test_scan_path = "/content/testscan/processed_lung2.npy"
    test_mask_path = "/content/testscan/create_ground_truth_masks2.npy"

    test_and_visualize_overlay(model_path, test_scan_path, test_mask_path)

import torch
import torch.nn as nn
import numpy as np
import os
import random
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Google Drive to access your saved model and data
drive.mount('/content/drive')

# ===================================================================
# 1. THE VNET MODEL ARCHITECTURE
# ===================================================================
def passthrough_block(in_channels, out_channels, kernel_size, stride, padding):
    return nn.Sequential(
        nn.Conv3d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm3d(out_channels)
    )

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ResidualBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels)
        )
        self.relu = nn.ReLU(inplace=True)
        self.passthrough = passthrough_block(in_channels, out_channels, kernel_size=1, stride=1, padding=0) if in_channels != out_channels else None

    def forward(self, x):
        residual = self.passthrough(x) if self.passthrough else x
        return self.relu(self.conv_block(x) + residual)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(VNet, self).__init__()
        self.down_conv1 = ResidualBlock(in_channels, 16)
        self.down_pool1 = passthrough_block(16, 32, kernel_size=2, stride=2, padding=0)

        self.down_conv2 = ResidualBlock(32, 32)
        self.down_pool2 = passthrough_block(32, 64, kernel_size=2, stride=2, padding=0)

        self.down_conv3 = ResidualBlock(64, 64)
        self.down_pool3 = passthrough_block(64, 128, kernel_size=2, stride=2, padding=0)

        self.down_conv4 = ResidualBlock(128, 128)
        self.down_pool4 = passthrough_block(128, 256, kernel_size=2, stride=2, padding=0)

        self.bottleneck = ResidualBlock(256, 256)

        self.up_deconv4 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.up_conv4 = ResidualBlock(256, 128)

        self.up_deconv3 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.up_conv3 = ResidualBlock(128, 64)

        self.up_deconv2 = nn.ConvTranspose3d(64, 32, kernel_size=2, stride=2)
        self.up_conv2 = ResidualBlock(64, 32)

        self.up_deconv1 = nn.ConvTranspose3d(32, 16, kernel_size=2, stride=2)
        self.up_conv1 = ResidualBlock(32, 16)

        self.final_conv = nn.Conv3d(16, out_channels, kernel_size=1)

    def forward(self, x):
        d1 = self.down_conv1(x)
        d2 = self.down_pool1(d1); d2 = self.down_conv2(d2)
        d3 = self.down_pool2(d2); d3 = self.down_conv3(d3)
        d4 = self.down_pool3(d3); d4 = self.down_conv4(d4)

        bottleneck_out = self.down_pool4(d4)
        bottleneck_out = self.bottleneck(bottleneck_out)

        u4 = self.up_deconv4(bottleneck_out); u4 = torch.cat((u4, d4), dim=1); u4 = self.up_conv4(u4)
        u3 = self.up_deconv3(u4); u3 = torch.cat((u3, d3), dim=1); u3 = self.up_conv3(u3)
        u2 = self.up_deconv2(u3); u2 = torch.cat((u2, d2), dim=1); u2 = self.up_conv2(u2)
        u1 = self.up_deconv1(u2); u1 = torch.cat((u1, d1), dim=1); u1 = self.up_conv1(u1)

        out = self.final_conv(u1)
        return out

# ===================================================================
# 2. DICE COEFFICIENT ACCURACY METRIC
# ===================================================================
def dice_coefficient(pred, target, smooth=1e-6):
    pred = pred.contiguous()
    target = target.contiguous()
    intersection = (pred * target).sum()
    dice = (2. * intersection + smooth) / (pred.sum() + target.sum() + smooth)
    return dice.item()

# ===================================================================
# 3. TEST AND VISUALIZATION FUNCTION
# ===================================================================
def test_and_visualize_overlay(model_path, test_scan_path, test_mask_path=None, patch_size=(96, 96, 96)):
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {DEVICE}")

    # --- Load the Model ---
    model = VNet().to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    print(f"✅ Model loaded successfully from {model_path}")

    # --- Load Test Data ---
    try:
        scan = np.load(test_scan_path)
    except FileNotFoundError:
        print(f"!!! Error: Could not find the test scan at: {test_scan_path}")
        return

    # Extract a fixed patch from the scan
    depth, height, width = scan.shape
    pd, ph, pw = patch_size
    z, y, x = (depth - pd) // 2, (height - ph) // 2, (width - pw) // 2
    scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]

    # Load mask if provided
    mask_patch = None
    if test_mask_path:
        try:
            mask = np.load(test_mask_path)
            mask_patch = mask[z:z+pd, y:y+ph, x:x+pw]
        except FileNotFoundError:
            print(f"!!! Error: Could not find the mask file at: {test_mask_path}")

    # Convert to tensor
    test_scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).unsqueeze(0).float().to(DEVICE)

    # --- Make Prediction and Calculate Score ---
    with torch.no_grad():
        prediction_logits = model(test_scan_tensor)
        prediction_probs = torch.sigmoid(prediction_logits)
        predicted_mask = (prediction_probs > 0.5).float()

    if test_mask_path and mask_patch is not None:
        test_mask_tensor = torch.from_numpy(mask_patch).unsqueeze(0).unsqueeze(0).float().to(DEVICE)
        score = dice_coefficient(predicted_mask, test_mask_tensor)
        print(f"\n✅ Dice Score for the test patch: {score:.4f}")
    else:
        print("\nNote: No Dice score calculated as no ground truth mask was provided.")

    # --- Visualization with Differentiated Overlay ---
    print("\n--- Generating Visualization ---")

    slice_index = patch_size[0] // 2
    scan_slice = scan_patch[slice_index, :, :]
    pred_mask_slice = predicted_mask.squeeze().cpu().numpy()[slice_index, :, :]

    fig, axes = plt.subplots(1, 2, figsize=(12, 6))

    # Plot 1: Original Scan
    axes[0].imshow(scan_slice, cmap='gray')
    axes[0].set_title('Original Input', fontsize=16)
    axes[0].axis('off')

    # Plot 2: Prediction with Red Overlay
    axes[1].imshow(scan_slice, cmap='gray')
    axes[1].imshow(pred_mask_slice, cmap='Reds', alpha=0.5)
    axes[1].set_title('Predicted Nodule (Red)', fontsize=16)
    axes[1].axis('off')

    plt.tight_layout()
    plt.show()

# ===================================================================
# 4. SCRIPT EXECUTION
# ===================================================================
if __name__ == '__main__':
    # !! UPDATE THIS PATH TO YOUR TRAINED MODEL IN GOOGLE DRIVE !!
    model_path = "/content/drive/My Drive/Lung Cancer Project/VNet_Nodule.pth"

    # These paths are for the files you will upload to Colab
    # !! UPDATE THESE PATHS TO YOUR ACTUAL TEST SCAN AND MASK FILES IN GOOGLE DRIVE !!
    test_scan_path = "/content/testscan/processed_lung2.npy"
    test_mask_path = "/content/testscan/create_ground_truth_masks2.npy"

    test_and_visualize_overlay(model_path, test_scan_path, test_mask_path)

import torch
import torch.nn as nn
import numpy as np
import os
import random
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Google Drive to access your saved model
drive.mount('/content/drive')

# ===================================================================
# 1. THE VNET MODEL ARCHITECTURE
# ===================================================================
def passthrough_block(in_channels, out_channels, kernel_size, stride, padding):
    return nn.Sequential(
        nn.Conv3d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm3d(out_channels)
    )

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ResidualBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm3d(out_channels)
        )
        self.relu = nn.ReLU(inplace=True)
        self.passthrough = passthrough_block(in_channels, out_channels, kernel_size=1, stride=1, padding=0) if in_channels != out_channels else None

    def forward(self, x):
        residual = self.passthrough(x) if self.passthrough else x
        return self.relu(self.conv_block(x) + residual)

class VNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(VNet, self).__init__()
        self.down_conv1 = ResidualBlock(in_channels, 16)
        self.down_pool1 = passthrough_block(16, 32, kernel_size=2, stride=2, padding=0)

        self.down_conv2 = ResidualBlock(32, 32)
        self.down_pool2 = passthrough_block(32, 64, kernel_size=2, stride=2, padding=0)

        self.down_conv3 = ResidualBlock(64, 64)
        self.down_pool3 = passthrough_block(64, 128, kernel_size=2, stride=2, padding=0)

        self.down_conv4 = ResidualBlock(128, 128)
        self.down_pool4 = passthrough_block(128, 256, kernel_size=2, stride=2, padding=0)

        self.bottleneck = ResidualBlock(256, 256)

        self.up_deconv4 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.up_conv4 = ResidualBlock(256, 128)

        self.up_deconv3 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.up_conv3 = ResidualBlock(128, 64)

        self.up_deconv2 = nn.ConvTranspose3d(64, 32, kernel_size=2, stride=2)
        self.up_conv2 = ResidualBlock(64, 32)

        self.up_deconv1 = nn.ConvTranspose3d(32, 16, kernel_size=2, stride=2)
        self.up_conv1 = ResidualBlock(32, 16)

        self.final_conv = nn.Conv3d(16, out_channels, kernel_size=1)

    def forward(self, x):
        d1 = self.down_conv1(x)
        d2 = self.down_pool1(d1); d2 = self.down_conv2(d2)
        d3 = self.down_pool2(d2); d3 = self.down_conv3(d3)
        d4 = self.down_pool3(d3); d4 = self.down_conv4(d4)

        bottleneck_out = self.down_pool4(d4)
        bottleneck_out = self.bottleneck(bottleneck_out)

        u4 = self.up_deconv4(bottleneck_out); u4 = torch.cat((u4, d4), dim=1); u4 = self.up_conv4(u4)
        u3 = self.up_deconv3(u4); u3 = torch.cat((u3, d3), dim=1); u3 = self.up_conv3(u3)
        u2 = self.up_deconv2(u3); u2 = torch.cat((u2, d2), dim=1); u2 = self.up_conv2(u2)
        u1 = self.up_deconv1(u2); u1 = torch.cat((u1, d1), dim=1); u1 = self.up_conv1(u1)

        out = self.final_conv(u1)
        return out

# ===================================================================
# 2. TEST AND VISUALIZATION FUNCTION
# ===================================================================
def test_and_visualize_combined(model_path, test_scan_path, test_mask_path, patch_size=(96, 96, 96)):
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {DEVICE}")

    # --- Load the Model ---
    model = VNet().to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    print(f"✅ Model loaded successfully from {model_path}")

    # --- Load Test Data ---
    try:
        scan = np.load(test_scan_path)
        gt_mask = np.load(test_mask_path)
    except FileNotFoundError:
        print(f"!!! Error: Could not find one or both of the files. Please check your paths.")
        return

    # Extract a fixed patch
    depth, height, width = scan.shape
    pd, ph, pw = patch_size
    z, y, x = (depth - pd) // 2, (height - ph) // 2, (width - pw) // 2
    scan_patch = scan[z:z+pd, y:y+ph, x:x+pw]
    gt_mask_patch = gt_mask[z:z+pd, y:y+ph, x:x+pw]

    # Convert to tensor
    test_scan_tensor = torch.from_numpy(scan_patch).unsqueeze(0).unsqueeze(0).float().to(DEVICE)

    # --- Make Prediction ---
    with torch.no_grad():
        prediction_logits = model(test_scan_tensor)
        prediction_probs = torch.sigmoid(prediction_logits)
        predicted_mask = (prediction_probs > 0.5).float()

    # Get 2D slices for visualization
    slice_index = patch_size[0] // 2
    scan_slice = scan_patch[slice_index, :, :]
    gt_mask_slice = gt_mask_patch[slice_index, :, :]
    pred_mask_slice = predicted_mask.squeeze().cpu().numpy()[slice_index, :, :]

    # --- Visualization ---
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    # Plot 1: Segmented Lung Nodule (Ground Truth)
    axes[0].imshow(gt_mask_slice, cmap='viridis')
    axes[0].set_title('Ground Truth Nodule', fontsize=16)
    axes[0].axis('off')

    # Plot 2: Predicted Nodule
    axes[1].imshow(pred_mask_slice, cmap='viridis')
    axes[1].set_title('Predicted Nodule', fontsize=16)
    axes[1].axis('off')

    # Plot 3: Overlay
    axes[2].imshow(scan_slice, cmap='gray')
    axes[2].imshow(pred_mask_slice, cmap='Reds', alpha=0.5)
    axes[2].set_title('Nodule Overlay', fontsize=16)
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

# ===================================================================
# 3. SCRIPT EXECUTION
# ===================================================================
if __name__ == '__main__':
    # !! UPDATE THESE PATHS !!
    model_path = "/content/drive/My Drive/Lung Cancer Project/VNet_Nodule.pth"
    test_scan_path = "/content/testscan/processed_lung2.npy"
    test_mask_path = "/content/testscan/create_ground_truth_masks2.npy"

    test_and_visualize_combined(model_path, test_scan_path, test_mask_path)